### ISSUE TITLE
Move tutorials and examples to Binder

### ISSUE THREAD

**Issue by fywu85** [flow-project/flow#284]
Move tutorials and examples to Binder: https://mybinder.org/

**Comment by jzf2101** [comment]
Hi from the binder team! We're actually trying to put it on binder right now.  Could you confirm that the installation instruction for ubuntu are correct? I tried to follow the instructions provided on the RTD and I think some Debian packages are left missing.  Local installation of sumo fails due to missing dependencies.

**Comment by fywu85** [comment]
Hi, thanks for reaching out. This is entirely possible as we are pushing for a release by mid December. A lot of pieces have been changed since the time when we wrote the installation instruction. Would you mind provide me with your os specs (Ubuntu version, etc.)? I will look into this and get back to you as soon as possible.

**Comment by fywu85** [comment]
Hi This totally falls through the cracks. I added the Dockerfile in the binder branch but could not successfully open it after build. Can you look at the issue [here](https://github.com/jupyterhub/binder/issues/158)?

**Comment by fywu85** [comment]
OK, the issue is resolved. Now the new problem is that Traci could not establish valid TCP connection when running on Binder. A most recent Binder build can be accessed [here](https://mybinder.org/v2/gh/flow-project/flow/binder). Will need to resolve this if we want to make it work on Binder. Working on it now.

**Comment by fywu85** [comment]
Closes #577
