### ISSUE TITLE
Aimsun_Next License?

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#397]
Hi I have successfully installed Aimsun according to the setup instructions. However, upon testing the installation with: 

python examples/aimsun/sugiyama.py

Aimsun licenser pops up requiring an activation key. Therefore I was wondering if it is a must requirement for completing the flow tutorials? If so, how can I go about obtaining a license?

Thanks.

**Comment by AboudyKreidieh** [comment]
hey @KidTrunks an aimsun license is only needed for the aimsun-specific components. These features are mostly self-contained, and so you should be able to run all other tutorials without experiencing any issues. I will try add a link on how an aimsun license can be acquired to the setup instructions later today, but in general you do not have to worry about this unless you want to work with aimsun specifically instead of sumo.

**Comment by AboudyKreidieh** [comment]
According to this link: https://www.aimsun.com/support-services/support/

```
For more information on the SUS including pricing and terms and conditions, please contact info@aimsun.com.
```

**Comment by AboudyKreidieh** [comment]
Yup, that’s right!

**Comment by KidTrunks** [comment]
I understand, thank you for the clarification. You may close it now!

**Comment by AboudyKreidieh** [comment]
Glad that helped!
