### ISSUE TITLE
Docker image is outdated

### ISSUE THREAD

**Issue by FarshadKoohifar** [flow-project/flow#402]
**Observation**
The following log file is created by running the Docker image that is provided as "latest". I have used the following commands to get it and run it.
`docker pull lucasfischerberkeley/flowdesktop`
`docker run -d -p 5901:5901 -p 6901:6901 -p 8888:8888 lucasfischerberkeley/flowdesktop`
I have run the following command inside the Docker container:
python flow/examples/rllib/green_wave.py &> log.txt
Note that I have modified the `SumoParams["sumo_binary"]` to be `"sumo"`, removing the GUI.
The resulting log file is attached below and shows a lot of problems happening in the simulation including teleportation, collision, and emergency stop.
[log.txt](https://github.com/flow-project/flow/files/2829287/log.txt)

**Question**
1. Why is that I do not get the same teleportation, collision, and emergency stop warnings when I do not use the Docker container and use the conda environment mode of local installation?
2. How out of date is the "latest" docker image? Should I avoid using? Are there major defects in the results that it produces?
3. How can I get the Ray and Flow version in the docker?

Thanks,
Farshad

**Comment by fywu85** [comment]
Hey, thanks for asking! To answer your questions:

1. The reason is very likely to be that the docker image is outdated. The root reason has to do with the underlying SUMO version and the internal configuration of the speed mode and lane change mode.
2. It is behind the master for about six months. We are truly sorry. We should have updated this long time ago. We will try to resolve the issue asap. Meanwhile, you may try to manually update flow, SUMO, and ray inside the docker image and see if the problem persists.
3. To get the version number, `import <package_name>` and then `print(<package_name>.__version__)`
