### ISSUE TITLE
Unused methods in green_wave.py

### ISSUE THREAD

**Issue by FarshadKoohifar** [flow-project/flow#403]
**Observation**
In [green_wave.py](https://github.com/flow-project/flow/blob/master/examples/rllib/green_wave.py), `gen_edges(row_num, col_num)` method is only used by `get_flow_params(col_num, row_num, additional_net_params)` which is not used at all.

**Question**
Why do we have these methods and how would I use them?

**Comment by AboudyKreidieh** [comment]
hi @FarshadKoohifar the gen_flow_params method is supposed to allow inflows of vehicles from the periphery edges instead of initializing the network with many vehicles. This is a really good point though! I will update this today with a variable that simplifies the use of this mehod.  More very soon.
