### ISSUE TITLE
expanded documentation for bottleneck environments

### ISSUE THREAD

**Issue by AboudyKreidieh** [flow-project/flow#436]
things that need to be documented:

- [x] BottleneckEnv: `additional_command`
- [x] BottleneckEnv: `ramp_meter_lane_change_control`
- [x] Bottleneck: `alinea`
- [x] Bottlneck: `apply_toll_bridge_control`
- [x] Bottleneck: `distance_to_bottleneck`
- [x] Bottleneck: delete `get_bottleneck_outflow_vehicles_per_hour`
- [x] Bottleneck: `get_bottleneck_density`
- [x] Bottleneck: `get_avg_bottleneck_velocity`
- [x] BottleckAccelEnv: `get_state`
- [x] BottleckAccelEnv: `additional_command`
- [x] DesiredVelocityEnv: `get_state`
- [x] DesiredVelocityEnv: `reset`

**Comment by kjang96** [comment]
This will be linked with #42

**Comment by kjang96** [comment]
@AboudyKreidieh  Where are the `distance_to_bottleneck`, `get_avg_bottleneck_velocity`? I ran a system search and couldn't find these. Maybe obsolete?

Also-- I left the following untouched, I think it would be better for @AboudyKreidieh or @eugenevinitsky  to document your code because I don't want to get it wrong: `ramp_meter_lane_change_control`,  `apply_toll_bridge_control`, BottleckAccelEnv's `get_state`, DesiredVelocityEnv's `get_state`.

**Comment by kjang96** [comment]
Leaving this open while the last 4 functions are undocumented, will proceed with merging the other documentation
