### ISSUE TITLE
How to use FLOW on other simulators?

### ISSUE THREAD

**Issue by seedjack** [flow-project/flow#703]
Hello,
I want to change the simulator since sumo doesn't meet my project. 
So,how to implement it? Do you have any suggestions?
thank you!

**Comment by Yasharzf** [comment]
In addition to Sumo, Flow supports Aimsun which is a commercial software.

**Comment by eugenevinitsky** [comment]
So, to build on this answer, @AboudyKreidieh and @Yasharzf have written flow so that it has a generic API that can be supported by any simulator (though it's a lot of work). If you look in flow/core, you can see a folder in which every folder has a base, aimsun, and traci file. The base file defines the API that every simulator has to implement, the traci and aimsun files are particular implementations of that API. You can use them as examples of how to do this. Which simulator were you thinking about using?

**Comment by seedjack** [comment]
Hi @eugenevinitsky , thank you for your  answer, I will try to do it refer to the traci file.

**Comment by eugenevinitsky** [comment]
Closed. Best of luck!
