### ISSUE TITLE
Feature Request for Multiagent_Rllib - Train Multiple AVs for stop-and-go Dissipating Controller

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#715]
**Feature Description**

Hi, I am trying to simulate a single-ring road scenario where multiple AVs are trained for a stop-and-go dissipating controller. 

The experiment will be identical to the stabilizing_the_ring experiments shown on the Flow Journal except with multiple AVs on a single ring. 
https://sites.google.com/view/ieee-tro-flow/home

Referring to the script located at: /flow/examples/rllib/multiagent_exps/multiagent_stabilizing_the_ring.py
I have successfully run the experiment for 1 AV on a single ring.

However, running multiple AVs on a single ring does not seem to work for this script. After looking at the environment of the script: MultiWaveAttenuationPOEnv
Located at: /flow/flow/multiagent_envs/loop/wave_attenuation.py 
I have realized that the class MultiWaveAttenuationPOEnv: 
_Is intended to work with Lord Of The Rings Scenario. Note that this environment currently only works when there is one autonomous vehicle on each ring._

Is there any other way to train multiple AVs to stabilize the single ring (stop-and-go dissipating controller) ? Or, is the current FLOW unable to simulate what I am trying to achieve ?

**Versions:**
FLOW: 0.4.1 dev
SUMO: v1_1_0+0000-2147d155b1

Sorry if this is not the correct place to post this question. I am not sure what category my question is. Any help would be greatly appreciated!

Regards.

**Comment by eugenevinitsky** [comment]
Hi @KidTrunks, apologies for the delay. You definitely can do this but will have to design a custom environment for this. The multiagent_stabilizing_the ring is slightly misnamed. Basically you need to take the stabilizing the ring apartment and you need to change it so that it outputs a dictionary ofrewards: one for each AV that you put into the system and returns a dictionary of observations one for each AV in the system. This should be pretty straightforward to by the building off the other multiagent examples and the stabilizing_the_ring example.

Let me know how it goes! I will eventually upload a version of this as well but it could be a while.

**Comment by KidTrunks** [comment]
Thank you for the clarification @eugenevinitsky. That makes a lot of sense now. 
However, I am not sure if I am capable of changing the output dictionary. 
But I will give it a try anyway. Cheers!
