### ISSUE TITLE
Run sumo-gui in WSL (Windows Subsystem for Linux) 

### ISSUE THREAD

**Issue by heraldiclily** [flow-project/flow#877]
Hello,
I have a problem when running "sumo-gui" to test sumo installation in ubuntu. I m using windows subsystem for linux (WSL).
Error message : "FXApp::openDisplay: unable to open display :0.0"
"which sumo" and "sumo --version" commands work well.

**Comment by TheMatheusLs** [comment]
Hello. Did you find the solution to this problem?

**Comment by temetski** [comment]
@heraldiclily this is expected: linux gui apps do not work out of the box in WSL. This is because WSL is running headless. https://github.com/flow-project/flow/issues/695#issuecomment-523216317 actually addresses this issue.

Here is another tutorial for running WSL gui apps in windows: https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242

**Comment by lylyjy** [comment]
Do you have solution to solve this problem?Can you run sumo-gui in wsl at last?
